# Install pre-commit hooks via:
# pre-commit install
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: end-of-file-fixer
      exclude: &exclude_pre_commit_hooks >
        (?x)^(
          examples/nwchemex_cc/pull.json|
          tests/data/.*|
        )$
    - id: mixed-line-ending
      exclude: *exclude_pre_commit_hooks
    - id: trailing-whitespace
      exclude: *exclude_pre_commit_hooks
    - id: check-json
      exclude: *exclude_pre_commit_hooks

- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      exclude: *exclude_pre_commit_hooks

- repo: local
  hooks:
  - id: pylint
    language: system
    types: [file, python]
    name: pylint
    description: "This hook runs the pylint static code analyzer"
    exclude: &exclude_files >
      (?x)^(
          docs/.*|
      )$
    entry: pylint
